import type { OperationCatalog } from '@tandemfolio/operation-contract'

export const markdownOperationCatalog = {
  format: 'markdown',
  operations: [
    {
      id: 'markdown.text.insert',
      format: 'markdown',
      family: 'text',
      summary: 'Insert text at the active Markdown selection.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string' },
        },
        required: ['text'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.text.replace_selection',
      format: 'markdown',
      family: 'text',
      summary: 'Replace the active Markdown selection.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string' },
        },
        required: ['text'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.selection.set',
      format: 'markdown',
      family: 'selection',
      summary: 'Set an explicit Markdown text selection.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          from: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          to: { type: 'integer', minimum: 1, maximum: 100_000_000 },
        },
        required: ['from', 'to'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          from: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          to: { type: 'integer', minimum: 1, maximum: 100_000_000 },
        },
        required: ['from', 'to'],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.text.set_marks',
      format: 'markdown',
      family: 'text',
      summary: 'Set the complete inline-mark state of one explicit Markdown range.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          from: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          to: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          marks: {
            type: 'object',
            properties: {
              bold: { type: 'boolean' },
              italic: { type: 'boolean' },
              strike: { type: 'boolean' },
              code: { type: 'boolean' },
              link: { type: ['string', 'null'], minLength: 1, maxLength: 4096 },
            },
            required: ['bold', 'italic', 'strike', 'code', 'link'],
            additionalProperties: false,
          },
        },
        required: ['from', 'to', 'marks'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.document.save',
      format: 'markdown',
      family: 'document',
      summary: 'Save the active Markdown document.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          saved: { type: 'boolean' },
          fileName: { type: 'string' },
        },
        required: ['saved', 'fileName'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.document.save_as',
      format: 'markdown',
      family: 'document',
      summary: 'Save the active Markdown document to a newly selected destination.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          saved: { type: 'boolean' },
          fileName: { type: 'string' },
        },
        required: ['saved', 'fileName'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.document.export_docx',
      format: 'markdown',
      family: 'document',
      summary: 'Export the active Markdown document as DOCX.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          exported: { type: 'boolean' },
          fileName: { type: 'string' },
        },
        required: ['exported', 'fileName'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.document.open_print_dialog',
      format: 'markdown',
      family: 'document',
      summary: 'Open the host print dialog for the active Markdown document.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          opened: { type: 'boolean' },
        },
        required: ['opened'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['view'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.document.set_auto_save',
      format: 'markdown',
      family: 'document',
      summary: 'Set the Markdown autosave preference to an explicit final state.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          enabled: { type: 'boolean' },
        },
        required: ['enabled'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          enabled: { type: 'boolean' },
        },
        required: ['enabled'],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['view', 'persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.document.load_staged',
      format: 'markdown',
      family: 'document',
      summary: 'Load staged Markdown bytes into the active editor.',
      visibility: 'internal',
      inputSchema: {
        type: 'object',
        properties: {
          blobId: { type: 'string' },
          name: { type: 'string' },
          size: { type: 'integer' },
          assetRootId: { type: 'string', minLength: 1, maxLength: 255 },
          data: {
            type: 'object',
            description: 'Hydrated ArrayBuffer supplied by the live-session host bridge.',
            properties: {},
            required: [],
            additionalProperties: false,
          },
        },
        required: ['blobId', 'name', 'size', 'data'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.list.set_type',
      format: 'markdown',
      family: 'list',
      summary: 'Set the list context of one addressed Markdown text block.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          textBlockIndex: { type: 'integer', minimum: 0, maximum: 1_000_000 },
          type: { type: 'string', enum: ['none', 'bullet', 'ordered', 'task'] },
        },
        required: ['textBlockIndex', 'type'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.history.undo',
      format: 'markdown',
      family: 'history',
      summary: 'Undo the latest Markdown editor transaction.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.block.set_type',
      format: 'markdown',
      family: 'block',
      summary: 'Set one addressed Markdown text block to an explicit final type.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          textBlockIndex: { type: 'integer', minimum: 0, maximum: 1_000_000 },
          type: {
            type: 'string',
            enum: [
              'paragraph',
              'heading_1',
              'heading_2',
              'heading_3',
              'heading_4',
              'heading_5',
              'heading_6',
              'quote',
              'code_block',
            ],
          },
        },
        required: ['textBlockIndex', 'type'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.history.redo',
      format: 'markdown',
      family: 'history',
      summary: 'Redo the latest Markdown editor transaction.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.divider.insert',
      format: 'markdown',
      family: 'divider',
      summary: 'Insert a divider at an explicit Markdown document position.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          position: { type: 'integer', minimum: 1, maximum: 100_000_000 },
        },
        required: ['position'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.table.insert',
      format: 'markdown',
      family: 'table',
      summary: 'Insert a bounded table at an explicit Markdown document position.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          position: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          rows: { type: 'integer', minimum: 1, maximum: 100 },
          columns: { type: 'integer', minimum: 1, maximum: 100 },
          headerRow: { type: 'boolean' },
        },
        required: ['position', 'rows', 'columns', 'headerRow'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.image.insert',
      format: 'markdown',
      family: 'image',
      summary: 'Insert one staged local image at an explicit Markdown position.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string', minLength: 1, maxLength: 1024 },
          position: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          alt: { type: 'string', maxLength: 1024 },
          title: { type: ['string', 'null'], minLength: 1, maxLength: 1024 },
        },
        required: ['path', 'position', 'alt', 'title'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.image.insert_staged',
      format: 'markdown',
      family: 'image',
      summary: 'Insert hydrated staged image bytes at an explicit Markdown position.',
      visibility: 'internal',
      inputSchema: {
        type: 'object',
        properties: {
          blobId: { type: 'string', minLength: 1, maxLength: 255 },
          name: { type: 'string', minLength: 1, maxLength: 255 },
          size: { type: 'integer', minimum: 1, maximum: 20_971_520 },
          data: {
            type: 'object',
            description: 'Hydrated ArrayBuffer supplied by the live-session host bridge.',
            properties: {},
            required: [],
            additionalProperties: false,
          },
          position: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          alt: { type: 'string', maxLength: 1024 },
          title: { type: ['string', 'null'], minLength: 1, maxLength: 1024 },
        },
        required: ['blobId', 'name', 'size', 'data', 'position', 'alt', 'title'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.frontmatter.set',
      format: 'markdown',
      family: 'frontmatter',
      summary: 'Set or remove the complete raw YAML frontmatter envelope.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          yaml: { type: 'string', maxLength: 1_048_576 },
        },
        required: ['yaml'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.table.update',
      format: 'markdown',
      family: 'table',
      summary: 'Apply one bounded mutation relative to an explicit Markdown table position.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          position: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          action: {
            type: 'string',
            enum: [
              'add_row_before',
              'add_row_after',
              'delete_row',
              'add_column_before',
              'add_column_after',
              'delete_column',
              'set_header_row',
              'delete_table',
            ],
          },
          headerRow: { type: ['boolean', 'null'] },
        },
        required: ['position', 'action', 'headerRow'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.block.update',
      format: 'markdown',
      family: 'block',
      summary: 'Apply one explicit top-level Markdown block mutation.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          blockIndex: { type: 'integer', minimum: 0, maximum: 1_000_000 },
          action: { type: 'string', enum: ['duplicate', 'delete', 'add_below', 'move'] },
          afterBlockIndex: { type: ['integer', 'null'], minimum: -1, maximum: 1_000_000 },
          content: { type: ['string', 'null'], maxLength: 65_536 },
        },
        required: ['blockIndex', 'action', 'afterBlockIndex', 'content'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'markdown.code_block.set_language',
      format: 'markdown',
      family: 'code_block',
      summary: 'Set one addressed Markdown code block to an explicit language.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          textBlockIndex: { type: 'integer', minimum: 0, maximum: 1_000_000 },
          language: {
            type: 'string',
            enum: [
              'plaintext',
              'bash',
              'c',
              'cpp',
              'csharp',
              'css',
              'diff',
              'dockerfile',
              'go',
              'graphql',
              'html',
              'java',
              'javascript',
              'json',
              'kotlin',
              'lua',
              'markdown',
              'objectivec',
              'php',
              'python',
              'r',
              'ruby',
              'rust',
              'scala',
              'scss',
              'sql',
              'swift',
              'typescript',
              'xml',
              'yaml',
            ],
          },
        },
        required: ['textBlockIndex', 'language'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document', 'selection'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
  ],
} as const satisfies OperationCatalog

export default markdownOperationCatalog
