import type { OperationCatalog } from '@tandemfolio/operation-contract'
import { SHAPE_GALLERY_GROUPS } from '@genoffice/ui'

const pptxObjectKinds = [
  'textbox',
  ...SHAPE_GALLERY_GROUPS.flatMap((group) => group.shapes.map((shape) => shape.prst)),
]

const pptxChartKinds = [
  'bar',
  'barStacked',
  'barPercentStacked',
  'barH',
  'line',
  'area',
  'pie',
  'doughnut',
  'scatter',
  'radar',
  'comboBarLine',
] as const

const pptxChartSeriesSchema = {
  type: 'object',
  properties: {
    name: { type: 'string', maxLength: 1_000 },
    values: {
      type: 'array',
      items: { type: 'number', minimum: -1e15, maximum: 1e15 },
      minItems: 1,
      maxItems: 10_000,
    },
  },
  required: ['name', 'values'],
  additionalProperties: false,
} as const

const pptxRunLinkSchema = {
  type: ['object', 'null'],
  properties: {
    kind: { type: 'string', enum: ['url', 'slide'] },
    url: { type: 'string', minLength: 1, maxLength: 8_192 },
    slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
  },
  required: ['kind'],
  additionalProperties: false,
} as const

const pptxEditRunSchema = {
  type: 'object',
  properties: {
    text: { type: 'string', maxLength: 1_000_000 },
    bold: { type: 'boolean' },
    italic: { type: 'boolean' },
    underline: { type: 'boolean' },
    fontSize: { type: 'number', minimum: 1, maximum: 1_000 },
    fontFamily: { type: 'string', minLength: 1, maxLength: 256 },
    color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
    strike: { type: 'boolean' },
    baseline: { type: 'number', minimum: -100_000, maximum: 100_000 },
    outline: {
      type: 'object',
      properties: {
        color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
        widthEmu: { type: 'number', minimum: 0, maximum: 9_144_000 },
      },
      required: ['color', 'widthEmu'],
      additionalProperties: false,
    },
    field: { type: 'string', minLength: 1, maxLength: 256 },
    srcRun: { type: 'integer', minimum: 0, maximum: 1_000_000 },
    link: pptxRunLinkSchema,
  },
  required: ['text'],
  additionalProperties: false,
} as const

const pptxEditParagraphSchema = {
  type: 'object',
  properties: {
    runs: {
      type: 'array',
      items: pptxEditRunSchema,
      minItems: 1,
      maxItems: 1_000,
    },
    align: { type: 'string', enum: ['left', 'center', 'right', 'justify'] },
    level: { type: 'integer', minimum: 0, maximum: 8 },
    srcPara: { type: 'integer', minimum: 0, maximum: 1_000_000 },
    bullet: { type: 'string', enum: ['char', 'number', 'none'] },
    bulletChar: { type: 'string', minLength: 1, maxLength: 8 },
    lineSpacingPct: { type: 'number', minimum: 1, maximum: 1_000 },
    spaceBeforePt: { type: 'number', minimum: 0, maximum: 1_000 },
    spaceAfterPt: { type: 'number', minimum: 0, maximum: 1_000 },
  },
  required: ['runs'],
  additionalProperties: false,
} as const

export const pptxOperationCatalog = {
  format: 'pptx',
  operations: [
    {
      id: 'pptx.animation.set',
      format: 'pptx',
      family: 'animation',
      summary: 'Replace one slide animation list using stable object ids.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          animations: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                objectId: { type: 'string', minLength: 1, maxLength: 256 },
                effect: {
                  type: 'string',
                  enum: [
                    'appear',
                    'fade',
                    'flyIn',
                    'wipe',
                    'wipeDown',
                    'splitIn',
                    'bounce',
                    'flipIn',
                    'zoom',
                    'pulse',
                    'spin',
                    'grow',
                    'teeter',
                    'disappear',
                    'fadeOut',
                    'flyOut',
                    'wipeOut',
                    'shrink',
                    'zoomOut',
                    'motionPath',
                  ],
                },
                trigger: { type: 'string', enum: ['onClick', 'withPrev', 'afterPrev'] },
                durationMs: { type: 'number', minimum: 0, maximum: 86_400_000 },
                delayMs: { type: 'number', minimum: 0, maximum: 86_400_000 },
                motionPath: { type: 'string', minLength: 1, maxLength: 100_000 },
                paragraph: { type: 'integer', minimum: 0, maximum: 100_000 },
              },
              required: ['objectId', 'effect', 'trigger', 'durationMs', 'delayMs'],
              additionalProperties: false,
            },
            maxItems: 10_000,
          },
        },
        required: ['slideIndex', 'animations'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { animationCount: { type: 'integer', minimum: 0, maximum: 10_000 } },
        required: ['animationCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.chart.add',
      format: 'pptx',
      family: 'chart',
      summary: 'Insert a chart with explicit bounded data and EMU geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          kind: { type: 'string', enum: pptxChartKinds },
          title: { type: 'string', maxLength: 10_000 },
          categories: {
            type: 'array',
            items: { type: 'string', maxLength: 10_000 },
            minItems: 1,
            maxItems: 10_000,
          },
          series: {
            type: 'array',
            items: pptxChartSeriesSchema,
            minItems: 1,
            maxItems: 1_000,
          },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
        },
        required: [
          'slideIndex',
          'kind',
          'categories',
          'series',
          'xEmu',
          'yEmu',
          'widthEmu',
          'heightEmu',
        ],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { chartId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['chartId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.chart.update',
      format: 'pptx',
      family: 'chart',
      summary: 'Update explicit chart data and style, with opt-in imported-chart simplification.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          chartId: { type: 'string', minLength: 1, maxLength: 256 },
          kind: { type: 'string', enum: pptxChartKinds },
          title: { type: 'string', maxLength: 10_000 },
          categories: {
            type: 'array',
            items: { type: 'string', maxLength: 10_000 },
            minItems: 1,
            maxItems: 10_000,
          },
          series: {
            type: 'array',
            items: pptxChartSeriesSchema,
            minItems: 1,
            maxItems: 1_000,
          },
          colors: {
            type: 'array',
            items: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
            minItems: 1,
            maxItems: 1_000,
          },
          legendPosition: {
            type: 'string',
            enum: ['bottom', 'top', 'right', 'left', 'none'],
          },
          dataLabels: { type: 'boolean' },
          gridlines: { type: 'boolean' },
          categoryAxisTitle: { type: 'string', maxLength: 10_000 },
          valueAxisTitle: { type: 'string', maxLength: 10_000 },
          gapWidthPercent: { type: 'number', minimum: 0, maximum: 500 },
          switchRowsAndColumns: { type: 'boolean' },
          pointColors: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                seriesIndex: { type: 'integer', minimum: 0, maximum: 999 },
                pointIndex: { type: 'integer', minimum: 0, maximum: 9_999 },
                color: {
                  type: ['string', 'null'],
                  pattern: '^#[0-9A-Fa-f]{6}$',
                },
              },
              required: ['seriesIndex', 'pointIndex', 'color'],
              additionalProperties: false,
            },
            maxItems: 100_000,
          },
          allowImportedSimplification: { type: 'boolean' },
        },
        required: ['slideIndex', 'chartId', 'allowImportedSimplification'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { chartId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['chartId'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.comment.add',
      format: 'pptx',
      family: 'comment',
      summary: 'Add one attributed comment to an explicit slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          author: { type: 'string', minLength: 1, maxLength: 256 },
          text: { type: 'string', minLength: 1, maxLength: 100_000 },
        },
        required: ['slideIndex', 'author', 'text'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          authorId: { type: 'integer', minimum: 0 },
          index: { type: 'integer', minimum: 0 },
        },
        required: ['authorId', 'index'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.comment.delete',
      format: 'pptx',
      family: 'comment',
      summary: 'Delete one comment by its stable author and comment indexes.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          authorId: { type: 'integer', minimum: 0, maximum: 1_000_000 },
          index: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        },
        required: ['slideIndex', 'authorId', 'index'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean', enum: [true] } },
        required: ['deleted'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.connector.set_endpoints',
      format: 'pptx',
      family: 'connector',
      summary: 'Set connector endpoint positions and explicit attachment final states.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          connectorId: { type: 'string', minLength: 1, maxLength: 256 },
          start: {
            type: 'object',
            properties: {
              xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
              yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
              attachment: {
                type: ['object', 'null'],
                properties: {
                  objectId: { type: 'string', minLength: 1, maxLength: 256 },
                  connectionPoint: { type: 'integer', minimum: 0, maximum: 255 },
                },
                required: ['objectId', 'connectionPoint'],
                additionalProperties: false,
              },
            },
            required: ['xEmu', 'yEmu', 'attachment'],
            additionalProperties: false,
          },
          end: {
            type: 'object',
            properties: {
              xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
              yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
              attachment: {
                type: ['object', 'null'],
                properties: {
                  objectId: { type: 'string', minLength: 1, maxLength: 256 },
                  connectionPoint: { type: 'integer', minimum: 0, maximum: 255 },
                },
                required: ['objectId', 'connectionPoint'],
                additionalProperties: false,
              },
            },
            required: ['xEmu', 'yEmu', 'attachment'],
            additionalProperties: false,
          },
        },
        required: ['slideIndex', 'connectorId', 'start', 'end'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.document.create_blank',
      format: 'pptx',
      family: 'document',
      summary:
        'Create a blank presentation. Replacing an opened, saved, restored, or edited document requires explicit user confirmation (confirmReplace: true); never use for a follow-up edit.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: { confirmReplace: { type: 'boolean' } },
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          opened: { type: 'boolean', enum: [true] },
          fileName: { type: 'string' },
          slideCount: { type: 'integer', enum: [1] },
        },
        required: ['opened', 'fileName', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: [],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.document.load_staged',
      format: 'pptx',
      family: 'document',
      summary: 'Load staged PPTX bytes into the active editor.',
      visibility: 'internal',
      inputSchema: {
        type: 'object',
        properties: {
          blobId: { type: 'string' },
          name: { type: 'string' },
          size: { type: 'integer' },
          data: {
            type: 'object',
            description: 'Hydrated ArrayBuffer supplied by the live-session host bridge.',
            properties: {},
            required: [],
            additionalProperties: false,
          },
        },
        required: ['blobId', 'name', 'size', 'data'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          opened: { type: 'boolean', enum: [true] },
          fileName: { type: 'string' },
        },
        required: ['opened', 'fileName'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.document.save',
      format: 'pptx',
      family: 'document',
      summary: 'Save the active PPTX presentation.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          saved: { type: 'boolean', enum: [true] },
          fileName: { type: 'string' },
        },
        required: ['saved', 'fileName'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.document.save_as',
      format: 'pptx',
      family: 'document',
      summary: 'Save a copy of the active presentation with an explicit PPTX file name.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          fileName: {
            type: 'string',
            minLength: 6,
            maxLength: 260,
            pattern: '^[^/\\\\]{1,255}\\.pptx$',
          },
        },
        required: ['fileName'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          saved: { type: 'boolean', enum: [true] },
          fileName: { type: 'string' },
        },
        required: ['saved', 'fileName'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.history.redo',
      format: 'pptx',
      family: 'history',
      summary: 'Redo the next native presentation history entry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          redone: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 1, maximum: 100_001 },
        },
        required: ['redone', 'slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.history.undo',
      format: 'pptx',
      family: 'history',
      summary: 'Undo the latest native presentation history entry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          undone: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 1, maximum: 100_001 },
        },
        required: ['undone', 'slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.hyperlink.set',
      format: 'pptx',
      family: 'hyperlink',
      summary: 'Set or clear one object hyperlink with an explicit target.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          target: {
            type: ['object', 'null'],
            properties: {
              kind: { type: 'string', enum: ['url', 'slide'] },
              url: { type: 'string', minLength: 1, maxLength: 8_192 },
              slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
            },
            required: ['kind'],
            additionalProperties: false,
          },
        },
        required: ['slideIndex', 'objectId', 'target'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { objectId: { type: 'string' } },
        required: ['objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.image.add_bytes',
      format: 'pptx',
      family: 'image',
      summary: 'Insert bounded raster image bytes with explicit EMU geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          data: {
            type: 'string',
            minLength: 4,
            maxLength: 27_962_028,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
          extension: {
            type: 'string',
            enum: ['png', 'jpg', 'jpeg', 'gif', 'bmp', 'webp', 'tif', 'tiff'],
          },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          name: { type: 'string', minLength: 1, maxLength: 1_000 },
        },
        required: ['slideIndex', 'data', 'extension', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { objectId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.image.replace_bytes',
      format: 'pptx',
      family: 'image',
      summary: 'Replace one picture backing image while explicitly preserving or clearing crop.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          pictureId: { type: 'string', minLength: 1, maxLength: 256 },
          data: {
            type: 'string',
            minLength: 4,
            maxLength: 27_962_028,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
          extension: {
            type: 'string',
            enum: ['png', 'jpg', 'jpeg', 'gif', 'bmp', 'webp', 'tif', 'tiff'],
          },
          preserveCrop: { type: 'boolean' },
        },
        required: ['slideIndex', 'pictureId', 'data', 'extension', 'preserveCrop'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.ink.add',
      format: 'pptx',
      family: 'ink',
      summary: 'Insert one bounded rasterized ink stroke with its vector payload.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          data: {
            type: 'string',
            minLength: 4,
            maxLength: 27_962_028,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
          payload: { type: 'string', minLength: 2, maxLength: 1_000_000 },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
        },
        required: ['slideIndex', 'data', 'payload', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { objectId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.master.object.delete',
      format: 'pptx',
      family: 'master',
      summary: 'Delete one explicit object from a retained master or layout part.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          partPath: {
            type: 'string',
            pattern: '^ppt/(slideMasters/slideMaster|slideLayouts/slideLayout)[0-9]+\\.xml$',
            maxLength: 256,
          },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['partPath', 'objectId'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean', enum: [true] } },
        required: ['deleted'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.master.object.set_fill',
      format: 'pptx',
      family: 'master',
      summary: 'Set an explicit fill on one master or layout object.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          partPath: {
            type: 'string',
            pattern: '^ppt/(slideMasters/slideMaster|slideLayouts/slideLayout)[0-9]+\\.xml$',
            maxLength: 256,
          },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          fill: {
            type: 'object',
            properties: {
              kind: { type: 'string', enum: ['none', 'solid', 'gradient'] },
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              from: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              to: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              angleDegrees: { type: 'number', minimum: -3_600, maximum: 3_600 },
              radial: { type: 'boolean' },
            },
            required: ['kind'],
            additionalProperties: false,
          },
        },
        required: ['partPath', 'objectId', 'fill'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.master.object.set_stroke',
      format: 'pptx',
      family: 'master',
      summary: 'Set or clear the stroke of one master or layout object.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          partPath: {
            type: 'string',
            pattern: '^ppt/(slideMasters/slideMaster|slideLayouts/slideLayout)[0-9]+\\.xml$',
            maxLength: 256,
          },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          stroke: {
            type: ['object', 'null'],
            properties: {
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              widthEmu: { type: 'number', minimum: 1, maximum: 9_144_000 },
            },
            required: ['color', 'widthEmu'],
            additionalProperties: false,
          },
        },
        required: ['partPath', 'objectId', 'stroke'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.master.object.set_transform',
      format: 'pptx',
      family: 'master',
      summary: 'Set one master or layout object transform in native EMU units.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          partPath: {
            type: 'string',
            pattern: '^ppt/(slideMasters/slideMaster|slideLayouts/slideLayout)[0-9]+\\.xml$',
            maxLength: 256,
          },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          rotationDegrees: { type: 'number', minimum: -3_600, maximum: 3_600 },
        },
        required: [
          'partPath',
          'objectId',
          'xEmu',
          'yEmu',
          'widthEmu',
          'heightEmu',
          'rotationDegrees',
        ],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.master.text.set_paragraphs',
      format: 'pptx',
      family: 'master',
      summary: 'Replace one master or layout text body with bounded rich text.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          partPath: {
            type: 'string',
            pattern: '^ppt/(slideMasters/slideMaster|slideLayouts/slideLayout)[0-9]+\\.xml$',
            maxLength: 256,
          },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          paragraphs: {
            type: 'array',
            items: pptxEditParagraphSchema,
            minItems: 1,
            maxItems: 1_000,
          },
        },
        required: ['partPath', 'objectId', 'paragraphs'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.media.add_bytes',
      format: 'pptx',
      family: 'media',
      summary: 'Embed bounded audio or video bytes with explicit EMU geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          kind: { type: 'string', enum: ['video', 'audio'] },
          data: {
            type: 'string',
            minLength: 4,
            maxLength: 139_810_136,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
          extension: {
            type: 'string',
            enum: ['mp4', 'm4v', 'mov', 'webm', 'avi', 'mp3', 'wav', 'm4a', 'aac', 'ogg'],
          },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          name: { type: 'string', minLength: 1, maxLength: 1_000 },
        },
        required: [
          'slideIndex',
          'kind',
          'data',
          'extension',
          'xEmu',
          'yEmu',
          'widthEmu',
          'heightEmu',
        ],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { objectId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['objectId'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.model3d.add_bytes',
      format: 'pptx',
      family: 'model3d',
      summary: 'Embed bounded GLB or glTF bytes with explicit poster geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          data: {
            type: 'string',
            minLength: 4,
            maxLength: 139_810_136,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
          extension: { type: 'string', enum: ['glb', 'gltf'] },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          name: { type: 'string', minLength: 1, maxLength: 1_000 },
        },
        required: ['slideIndex', 'data', 'extension', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { objectId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['objectId'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.notes.set',
      format: 'pptx',
      family: 'notes',
      summary: 'Replace one slide speaker notes with explicit text.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          text: { type: 'string', maxLength: 1_000_000 },
        },
        required: ['slideIndex', 'text'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.add',
      format: 'pptx',
      family: 'object',
      summary: 'Insert a bounded text box, shape, line, or connector with native EMU geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          kind: { type: 'string', enum: pptxObjectKinds },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 0, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 0, maximum: 914_400_000 },
          text: { type: 'string', maxLength: 1_000_000 },
          paragraphs: {
            type: 'array',
            items: pptxEditParagraphSchema,
            minItems: 1,
            maxItems: 1_000,
          },
          fillColor: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
          stroke: {
            type: 'object',
            properties: {
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              widthEmu: { type: 'number', minimum: 1, maximum: 9_144_000 },
            },
            required: ['color', 'widthEmu'],
            additionalProperties: false,
          },
        },
        required: ['slideIndex', 'kind', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          added: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string' },
        },
        required: ['added', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.copy_to',
      format: 'pptx',
      family: 'object',
      summary: 'Copy explicit objects to a destination slide without hidden clipboard state.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          sourceSlideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
          destinationSlideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          deltaXEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          deltaYEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
        },
        required: [
          'sourceSlideIndex',
          'objectIds',
          'destinationSlideIndex',
          'deltaXEmu',
          'deltaYEmu',
        ],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
        },
        required: ['objectIds'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.delete',
      format: 'pptx',
      family: 'object',
      summary: 'Delete one explicit top-level object from a slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['slideIndex', 'objectId'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          deleted: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string' },
        },
        required: ['deleted', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.duplicate',
      format: 'pptx',
      family: 'object',
      summary: 'Duplicate explicit objects by one bounded EMU offset.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
          deltaXEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          deltaYEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
        },
        required: ['slideIndex', 'objectIds', 'deltaXEmu', 'deltaYEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
        },
        required: ['objectIds'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.group',
      format: 'pptx',
      family: 'object',
      summary: 'Group two or more explicit top-level editable objects.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 2,
            maxItems: 100,
          },
        },
        required: ['slideIndex', 'objectIds'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          grouped: { type: 'boolean', enum: [true] },
          groupId: { type: 'string' },
        },
        required: ['grouped', 'groupId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.move_selection',
      format: 'pptx',
      family: 'object',
      summary: 'Move every selected top-level object by an explicit EMU delta.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          deltaXEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          deltaYEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
        },
        required: ['deltaXEmu', 'deltaYEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          moved: { type: 'integer', minimum: 1, maximum: 100 },
        },
        required: ['moved'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document', 'selection'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.reorder',
      format: 'pptx',
      family: 'object',
      summary: 'Move one explicit top-level object in the slide z-order.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          position: { type: 'string', enum: ['front', 'back', 'forward', 'backward'] },
        },
        required: ['slideIndex', 'objectId', 'position'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { reordered: { type: 'boolean', enum: [true] } },
        required: ['reordered'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.set_fill',
      format: 'pptx',
      family: 'object',
      summary: 'Set an explicit none, solid, or two-stop gradient object fill.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          fill: {
            type: 'object',
            properties: {
              kind: { type: 'string', enum: ['none', 'solid', 'gradient'] },
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              from: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              to: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              angleDegrees: { type: 'number', minimum: -3_600, maximum: 3_600 },
              radial: { type: 'boolean' },
            },
            required: ['kind'],
            additionalProperties: false,
          },
        },
        required: ['slideIndex', 'objectId', 'fill'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          updated: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0 },
          objectId: { type: 'string' },
        },
        required: ['updated', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.set_flip',
      format: 'pptx',
      family: 'object',
      summary: 'Set the final horizontal and/or vertical flip state of explicit objects.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          horizontal: { type: 'boolean' },
          vertical: { type: 'boolean' },
        },
        required: ['slideIndex', 'objectIds'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          changed: { type: 'integer', minimum: 0, maximum: 100 },
        },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.set_image_fill',
      format: 'pptx',
      family: 'object',
      summary: 'Set a bounded embedded image as one explicit shape fill.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          data: {
            type: 'string',
            minLength: 4,
            maxLength: 27_962_028,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
          extension: {
            type: 'string',
            enum: ['png', 'jpg', 'jpeg', 'gif', 'bmp', 'webp', 'tif', 'tiff'],
          },
        },
        required: ['slideIndex', 'objectId', 'data', 'extension'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          updated: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['updated', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.set_stroke',
      format: 'pptx',
      family: 'object',
      summary: 'Set or clear an explicit object stroke.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          stroke: {
            type: ['object', 'null'],
            properties: {
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              widthPt: { type: 'number', minimum: 0.01, maximum: 1_000 },
              dash: {
                type: 'string',
                enum: [
                  'solid',
                  'dot',
                  'dash',
                  'lgDash',
                  'dashDot',
                  'lgDashDot',
                  'lgDashDotDot',
                  'sysDot',
                  'sysDash',
                  'sysDashDot',
                  'sysDashDotDot',
                ],
              },
            },
            required: ['color', 'widthPt'],
            additionalProperties: false,
          },
        },
        required: ['slideIndex', 'objectId', 'stroke'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          updated: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0 },
          objectId: { type: 'string' },
        },
        required: ['updated', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.set_transform',
      format: 'pptx',
      family: 'object',
      summary: 'Set one object geometry using document-native EMU coordinates.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          rotationDegrees: { type: 'number', minimum: -3_600, maximum: 3_600 },
        },
        required: [
          'slideIndex',
          'objectId',
          'xEmu',
          'yEmu',
          'widthEmu',
          'heightEmu',
          'rotationDegrees',
        ],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          transformed: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string' },
        },
        required: ['transformed', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.set_transforms',
      format: 'pptx',
      family: 'object',
      summary: 'Set bounded explicit EMU geometry for multiple top-level objects atomically.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objects: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                objectId: { type: 'string', minLength: 1, maxLength: 256 },
                xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
                yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
                widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
                heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
                rotationDegrees: { type: 'number', minimum: -3_600, maximum: 3_600 },
              },
              required: ['objectId', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu', 'rotationDegrees'],
              additionalProperties: false,
            },
            minItems: 1,
            maxItems: 100,
          },
        },
        required: ['slideIndex', 'objects'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { changed: { type: 'integer', minimum: 1, maximum: 100 } },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.object.ungroup',
      format: 'pptx',
      family: 'object',
      summary: 'Promote one explicit group object children to the slide top level.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['slideIndex', 'groupId'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { ungrouped: { type: 'integer', minimum: 1, maximum: 10_000 } },
        required: ['ungrouped'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.paragraph.set_format',
      format: 'pptx',
      family: 'paragraph',
      summary: 'Apply paragraph formatting to text-bearing objects.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          bullet: { type: 'string', enum: ['char', 'number', 'none'] },
          bulletChar: { type: 'string', minLength: 1, maxLength: 8 },
          bulletHangEmu: {
            type: 'number',
            minimum: -9_144_000,
            maximum: 9_144_000,
          },
          bulletSizePct: { type: 'number', minimum: 1, maximum: 400 },
          bulletColor: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
          lineSpacingPct: { type: 'number', minimum: 1, maximum: 1_000 },
          spaceBeforePt: { type: 'number', minimum: 0, maximum: 1_000 },
          spaceAfterPt: { type: 'number', minimum: 0, maximum: 1_000 },
          align: { type: 'string', enum: ['left', 'center', 'right', 'justify'] },
          indentDelta: { type: 'integer', enum: [-1, 1] },
        },
        required: ['slideIndex', 'objectIds'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          changed: { type: 'integer', minimum: 1, maximum: 100 },
        },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.picture.set_crop',
      format: 'pptx',
      family: 'picture',
      summary: 'Set or clear picture crop ratios and optionally its final EMU frame.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          pictureId: { type: 'string', minLength: 1, maxLength: 256 },
          crop: {
            type: ['object', 'null'],
            properties: {
              left: { type: 'number', minimum: 0, maximum: 1 },
              top: { type: 'number', minimum: 0, maximum: 1 },
              right: { type: 'number', minimum: 0, maximum: 1 },
              bottom: { type: 'number', minimum: 0, maximum: 1 },
            },
            required: ['left', 'top', 'right', 'bottom'],
            additionalProperties: false,
          },
          frame: {
            type: 'object',
            properties: {
              xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
              yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
              widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
              heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
            },
            required: ['xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
            additionalProperties: false,
          },
        },
        required: ['slideIndex', 'pictureId', 'crop'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.picture.set_opacity',
      format: 'pptx',
      family: 'picture',
      summary: 'Set one picture opacity to an explicit final value.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          pictureId: { type: 'string', minLength: 1, maxLength: 256 },
          opacity: { type: 'number', minimum: 0, maximum: 1 },
        },
        required: ['slideIndex', 'pictureId', 'opacity'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.section.add',
      format: 'pptx',
      family: 'section',
      summary: 'Add a named section before an explicit slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          beforeSlideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          name: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['beforeSlideIndex', 'name'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { sectionCount: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['sectionCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.section.move',
      format: 'pptx',
      family: 'section',
      summary: 'Move one section and its slides one position.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          sectionId: { type: 'string', minLength: 1, maxLength: 256 },
          direction: { type: 'string', enum: ['up', 'down'] },
        },
        required: ['sectionId', 'direction'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { sectionCount: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['sectionCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.section.remove',
      format: 'pptx',
      family: 'section',
      summary: 'Remove one section while retaining its slides.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: { sectionId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['sectionId'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { sectionCount: { type: 'integer', minimum: 0, maximum: 100_001 } },
        required: ['sectionCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.section.rename',
      format: 'pptx',
      family: 'section',
      summary: 'Rename one explicit section.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          sectionId: { type: 'string', minLength: 1, maxLength: 256 },
          name: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['sectionId', 'name'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { sectionCount: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['sectionCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.selection.set',
      format: 'pptx',
      family: 'selection',
      summary: 'Set the active slide and selected top-level objects.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 0,
            maxItems: 100,
          },
        },
        required: ['slideIndex', 'objectIds'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          selected: { type: 'integer', minimum: 0, maximum: 100 },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
        },
        required: ['selected', 'slideIndex'],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['selection'],
      mutates: false,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.add_blank',
      format: 'pptx',
      family: 'slide',
      summary: 'Insert a blank slide after an existing slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          afterSlideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
        },
        required: ['afterSlideIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 1, maximum: 100_001 },
        },
        required: ['slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.add_with_layout',
      format: 'pptx',
      family: 'slide',
      summary: 'Insert a slide after an existing slide using an explicit retained layout.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          afterSlideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          layoutPath: { type: 'string', minLength: 1, maxLength: 1_024 },
        },
        required: ['afterSlideIndex', 'layoutPath'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 2, maximum: 100_001 },
        },
        required: ['slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.apply_header_footer',
      format: 'pptx',
      family: 'slide',
      summary: 'Apply an explicit footer, slide-number, and date state to all slides.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          footer: { type: ['string', 'null'], maxLength: 10_000 },
          slideNumber: { type: 'boolean' },
          date: { type: ['string', 'null'], maxLength: 10_000 },
          automaticDate: { type: 'boolean' },
        },
        required: ['footer', 'slideNumber', 'date', 'automaticDate'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { changed: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.copy_to',
      format: 'pptx',
      family: 'slide',
      summary: 'Copy one explicit slide without hidden clipboard state.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          sourceSlideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          afterSlideIndex: { type: 'integer', minimum: -1, maximum: 100_000 },
          mode: { type: 'string', enum: ['theme', 'source', 'picture'] },
          pictureData: {
            type: 'string',
            minLength: 4,
            maxLength: 27_962_028,
            pattern: '^[A-Za-z0-9+/]*={0,2}$',
          },
        },
        required: ['sourceSlideIndex', 'afterSlideIndex', 'mode'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 1, maximum: 100_001 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.delete',
      format: 'pptx',
      family: 'slide',
      summary: 'Delete a slide while retaining at least one slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
        },
        required: ['slideIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 1, maximum: 100_000 },
        },
        required: ['slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.duplicate',
      format: 'pptx',
      family: 'slide',
      summary: 'Duplicate a slide after itself, optionally clearing copied text.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          clearText: { type: 'boolean' },
        },
        required: ['slideIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 2, maximum: 100_001 },
        },
        required: ['slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.move',
      format: 'pptx',
      family: 'slide',
      summary: 'Move a slide to an explicit destination index.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          fromIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          toIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
        },
        required: ['fromIndex', 'toIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          slideCount: { type: 'integer', minimum: 1, maximum: 100_001 },
        },
        required: ['slideIndex', 'slideCount'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.set_advance_times',
      format: 'pptx',
      family: 'slide',
      summary: 'Set or clear explicit auto-advance times on bounded slides.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slides: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
                milliseconds: { type: ['number', 'null'], minimum: 0, maximum: 86_400_000 },
              },
              required: ['slideIndex', 'milliseconds'],
              additionalProperties: false,
            },
            minItems: 1,
            maxItems: 10_000,
          },
        },
        required: ['slides'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { changed: { type: 'integer', minimum: 1, maximum: 10_000 } },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.set_background',
      format: 'pptx',
      family: 'slide',
      summary: 'Set a solid background on one slide or every slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          scope: { type: 'string', enum: ['slide', 'all'] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
        },
        required: ['scope', 'color'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          changed: { type: 'integer', minimum: 1, maximum: 100_001 },
        },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.set_hidden',
      format: 'pptx',
      family: 'slide',
      summary: 'Set one slide hidden state explicitly.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          hidden: { type: 'boolean' },
        },
        required: ['slideIndex', 'hidden'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.set_layout',
      format: 'pptx',
      family: 'slide',
      summary: 'Set one slide layout path or reset inherited placeholder geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          layoutPath: { type: ['string', 'null'], minLength: 1, maxLength: 1_024 },
        },
        required: ['slideIndex', 'layoutPath'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.set_size',
      format: 'pptx',
      family: 'slide',
      summary: 'Set the presentation canvas size in EMU and scale slide content.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          widthEmu: { type: 'integer', minimum: 914_400, maximum: 91_440_000 },
          heightEmu: { type: 'integer', minimum: 914_400, maximum: 91_440_000 },
        },
        required: ['widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { changed: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.slide.set_transition',
      format: 'pptx',
      family: 'slide',
      summary: 'Set an explicit transition on one slide or every slide.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          scope: { type: 'string', enum: ['slide', 'all'] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          transition: {
            type: 'string',
            enum: [
              'none',
              'morph',
              'fade',
              'push',
              'wipe',
              'split',
              'circle',
              'cover',
              'pull',
              'dissolve',
              'zoom',
              'random',
            ],
          },
        },
        required: ['scope', 'transition'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { changed: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.smartart.add',
      format: 'pptx',
      family: 'smartart',
      summary: 'Insert an editable SmartArt-compatible shape group with explicit EMU geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          layout: {
            type: 'string',
            enum: ['list', 'process', 'cycle', 'hierarchy', 'pyramid', 'matrix', 'venn'],
          },
          items: {
            type: 'array',
            items: { type: 'string', maxLength: 10_000 },
            minItems: 1,
            maxItems: 8,
          },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
        },
        required: ['slideIndex', 'layout', 'items', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { objectId: { type: 'string', minLength: 1, maxLength: 256 } },
        required: ['objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.add',
      format: 'pptx',
      family: 'table',
      summary: 'Insert a bounded table with explicit EMU geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          rows: { type: 'integer', minimum: 1, maximum: 1_000 },
          columns: { type: 'integer', minimum: 1, maximum: 1_000 },
          xEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          yEmu: { type: 'number', minimum: -914_400_000, maximum: 914_400_000 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
        },
        required: ['slideIndex', 'rows', 'columns', 'xEmu', 'yEmu', 'widthEmu', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { tableId: { type: 'string' } },
        required: ['tableId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.edit_structure',
      format: 'pptx',
      family: 'table',
      summary: 'Insert or delete one explicit table row or column.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          action: {
            type: 'string',
            enum: ['insert-row', 'delete-row', 'insert-col', 'delete-col'],
          },
          index: { type: 'integer', minimum: 0, maximum: 999 },
          before: { type: 'boolean' },
        },
        required: ['slideIndex', 'tableId', 'action', 'index'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { tableId: { type: 'string' } },
        required: ['tableId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.merge_cells',
      format: 'pptx',
      family: 'table',
      summary: 'Merge right/down from one cell or split its merged region.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          action: { type: 'string', enum: ['merge-right', 'merge-down', 'split'] },
          row: { type: 'integer', minimum: 0, maximum: 999 },
          column: { type: 'integer', minimum: 0, maximum: 999 },
        },
        required: ['slideIndex', 'tableId', 'action', 'row', 'column'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { tableId: { type: 'string' } },
        required: ['tableId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.set_cell_anchor',
      format: 'pptx',
      family: 'table',
      summary: 'Set one table cell vertical text anchor.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          row: { type: 'integer', minimum: 0, maximum: 999 },
          column: { type: 'integer', minimum: 0, maximum: 999 },
          anchor: { type: 'string', enum: ['top', 'middle', 'bottom'] },
        },
        required: ['slideIndex', 'tableId', 'row', 'column', 'anchor'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.set_cell_content',
      format: 'pptx',
      family: 'table',
      summary: 'Replace one table cell with bounded rich-text paragraphs.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          row: { type: 'integer', minimum: 0, maximum: 999 },
          column: { type: 'integer', minimum: 0, maximum: 999 },
          paragraphs: {
            type: 'array',
            items: pptxEditParagraphSchema,
            minItems: 1,
            maxItems: 1_000,
          },
        },
        required: ['slideIndex', 'tableId', 'row', 'column', 'paragraphs'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.set_column_width',
      format: 'pptx',
      family: 'table',
      summary: 'Set one table column width in EMU.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          column: { type: 'integer', minimum: 0, maximum: 999 },
          widthEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
        },
        required: ['slideIndex', 'tableId', 'column', 'widthEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.set_row_height',
      format: 'pptx',
      family: 'table',
      summary: 'Set one table row height in EMU.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          row: { type: 'integer', minimum: 0, maximum: 999 },
          heightEmu: { type: 'number', minimum: 1, maximum: 914_400_000 },
        },
        required: ['slideIndex', 'tableId', 'row', 'heightEmu'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.table.set_style',
      format: 'pptx',
      family: 'table',
      summary: 'Apply a bounded preset or direct table style patch.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          tableId: { type: 'string', minLength: 1, maxLength: 256 },
          styleName: {
            type: 'string',
            enum: [
              'none',
              'lightGrid',
              'zebraBlue',
              'zebraGray',
              'headerDarkBlue',
              'headerOrange',
              'noBorder',
              'fullBorder',
            ],
          },
          firstRow: { type: 'boolean' },
          bandedRows: { type: 'boolean' },
          shadingColor: { type: ['string', 'null'], pattern: '^(?:#[0-9A-Fa-f]{6}|none)$' },
          borderColor: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
          borderWidthPt: { type: 'number', minimum: 0.01, maximum: 1_000 },
          borderPreset: { type: 'string', enum: ['all', 'none'] },
          cells: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                row: { type: 'integer', minimum: 0, maximum: 999 },
                column: { type: 'integer', minimum: 0, maximum: 999 },
              },
              required: ['row', 'column'],
              additionalProperties: false,
            },
            minItems: 1,
            maxItems: 10_000,
          },
        },
        required: ['slideIndex', 'tableId'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { tableId: { type: 'string' } },
        required: ['tableId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.text.replace_all',
      format: 'pptx',
      family: 'text',
      summary: 'Find and replace text across an explicit presentation scope.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          find: { type: 'string', minLength: 1, maxLength: 100_000 },
          replace: { type: 'string', maxLength: 1_000_000 },
          matchCase: { type: 'boolean' },
          firstOnly: { type: 'boolean' },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
        },
        required: ['find', 'replace'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          changed: { type: 'integer', minimum: 0, maximum: 100_000_000 },
        },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.text.replace_selection',
      format: 'pptx',
      family: 'text',
      summary: 'Replace the text of every selected editable top-level object.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string', maxLength: 1_000_000 },
        },
        required: ['text'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          changed: { type: 'integer', minimum: 1, maximum: 100 },
        },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document', 'selection'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.text.set_font',
      format: 'pptx',
      family: 'text',
      summary: 'Apply explicit font properties to text-bearing objects, optionally within a group.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectIds: {
            type: 'array',
            items: { type: 'string', minLength: 1, maxLength: 256 },
            minItems: 1,
            maxItems: 100,
          },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          fontFamily: { type: 'string', minLength: 1, maxLength: 256 },
          fontSizePt: { type: 'number', minimum: 1, maximum: 1_000 },
          bold: { type: 'boolean' },
          italic: { type: 'boolean' },
          underline: { type: 'boolean' },
          strike: { type: 'boolean' },
          color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
        },
        required: ['slideIndex', 'objectIds'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          changed: { type: 'integer', minimum: 1, maximum: 100 },
        },
        required: ['changed'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.text.set_paragraphs',
      format: 'pptx',
      family: 'text',
      summary: 'Replace one object rich-text body with explicit paragraph and run structure.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          groupId: { type: 'string', minLength: 1, maxLength: 256 },
          paragraphs: {
            type: 'array',
            items: pptxEditParagraphSchema,
            minItems: 1,
            maxItems: 1_000,
          },
        },
        required: ['slideIndex', 'objectId', 'paragraphs'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          updated: { type: 'boolean', enum: [true] },
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string' },
        },
        required: ['updated', 'slideIndex', 'objectId'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.text.set_vertical_anchor',
      format: 'pptx',
      family: 'text',
      summary: 'Set the vertical text anchor of one explicit text-capable object.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          slideIndex: { type: 'integer', minimum: 0, maximum: 100_000 },
          objectId: { type: 'string', minLength: 1, maxLength: 256 },
          anchor: { type: 'string', enum: ['top', 'middle', 'bottom'] },
        },
        required: ['slideIndex', 'objectId', 'anchor'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pptx.theme.apply',
      format: 'pptx',
      family: 'theme',
      summary: 'Apply one bounded built-in theme to the whole presentation.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          preset: {
            type: 'string',
            enum: ['office', 'ember', 'indigo', 'forest', 'cream', 'rose', 'graphite', 'midnight'],
          },
        },
        required: ['preset'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { changedSlides: { type: 'integer', minimum: 1, maximum: 100_001 } },
        required: ['changedSlides'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
  ],
} as const satisfies OperationCatalog

export default pptxOperationCatalog
