// Modified by TandemFolio contributors: browser-native workbook merge copy.
import { defineStrings } from '@genoffice/i18n'

export const nativeMergeStrings = defineStrings({
  zh: { appMergeWorkbooks: '合并工作簿', appMergeWorkbooksTip: '将其他 Excel 文件的工作表并入当前工作簿', appMergeWorkbooksPicking: '选择要合并的文件…', appMergeWorkbooksReading: '正在导入 {file} 的 {sheet}…', appMergeWorkbooksDone: '已合并 {files} 个文件的 {sheets} 张工作表（公式已转为数值）。', appMergeWorkbooksFailed: '合并工作簿失败。', appMergeWorkbooksInsertFailed: '无法创建工作表 {sheet}。', appMergeWorkbooksLocked: '工作簿结构已锁定，暂时无法合并工作簿。' },
  en: { appMergeWorkbooks: 'Merge Workbooks', appMergeWorkbooksTip: 'Append sheets from other Excel files into this workbook', appMergeWorkbooksPicking: 'Choose files to merge…', appMergeWorkbooksReading: 'Importing {sheet} from {file}…', appMergeWorkbooksDone: 'Merged {sheets} sheets from {files} files (formulas imported as values).', appMergeWorkbooksFailed: 'Merging workbooks failed.', appMergeWorkbooksInsertFailed: 'Could not create sheet {sheet}.', appMergeWorkbooksLocked: 'The workbook structure is locked; merging is unavailable.' },
  ja: { appMergeWorkbooks: 'ブックの結合', appMergeWorkbooksTip: '他の Excel ファイルのシートをこのブックに追加します', appMergeWorkbooksPicking: '結合するファイルを選択…', appMergeWorkbooksReading: '{file} の {sheet} をインポート中…', appMergeWorkbooksDone: '{files} 個のファイルから {sheets} 枚のシートを結合しました（数式は値としてインポート）。', appMergeWorkbooksFailed: 'ブックの結合に失敗しました。', appMergeWorkbooksInsertFailed: 'シート {sheet} を作成できませんでした。', appMergeWorkbooksLocked: 'ブック構造がロックされているため結合できません。' },
  ko: { appMergeWorkbooks: '통합 문서 병합', appMergeWorkbooksTip: '다른 Excel 파일의 시트를 현재 통합 문서에 추가합니다', appMergeWorkbooksPicking: '병합할 파일 선택…', appMergeWorkbooksReading: '{file}의 {sheet} 가져오는 중…', appMergeWorkbooksDone: '{files}개 파일에서 시트 {sheets}장을 병합했습니다(수식은 값으로 가져옴).', appMergeWorkbooksFailed: '통합 문서 병합에 실패했습니다.', appMergeWorkbooksInsertFailed: '시트 {sheet}을(를) 만들 수 없습니다.', appMergeWorkbooksLocked: '통합 문서 구조가 잠겨 있어 병합할 수 없습니다.' },
  fr: { appMergeWorkbooks: 'Fusionner des classeurs', appMergeWorkbooksTip: "Ajouter les feuilles d'autres fichiers Excel à ce classeur", appMergeWorkbooksPicking: 'Choisissez les fichiers à fusionner…', appMergeWorkbooksReading: 'Import de {sheet} depuis {file}…', appMergeWorkbooksDone: '{sheets} feuilles de {files} fichiers fusionnées (formules importées comme valeurs).', appMergeWorkbooksFailed: 'Échec de la fusion des classeurs.', appMergeWorkbooksInsertFailed: 'Impossible de créer la feuille {sheet}.', appMergeWorkbooksLocked: 'La structure du classeur est verrouillée ; fusion indisponible.' },
  de: { appMergeWorkbooks: 'Arbeitsmappen zusammenführen', appMergeWorkbooksTip: 'Blätter aus anderen Excel-Dateien in diese Arbeitsmappe übernehmen', appMergeWorkbooksPicking: 'Dateien zum Zusammenführen wählen…', appMergeWorkbooksReading: 'Importiere {sheet} aus {file}…', appMergeWorkbooksDone: '{sheets} Blätter aus {files} Dateien zusammengeführt (Formeln als Werte importiert).', appMergeWorkbooksFailed: 'Zusammenführen der Arbeitsmappen fehlgeschlagen.', appMergeWorkbooksInsertFailed: 'Blatt {sheet} konnte nicht erstellt werden.', appMergeWorkbooksLocked: 'Die Arbeitsmappenstruktur ist geschützt; Zusammenführen ist nicht verfügbar.' },
  es: { appMergeWorkbooks: 'Combinar libros', appMergeWorkbooksTip: 'Añadir las hojas de otros archivos de Excel a este libro', appMergeWorkbooksPicking: 'Elige los archivos para combinar…', appMergeWorkbooksReading: 'Importando {sheet} de {file}…', appMergeWorkbooksDone: 'Se combinaron {sheets} hojas de {files} archivos (fórmulas importadas como valores).', appMergeWorkbooksFailed: 'No se pudieron combinar los libros.', appMergeWorkbooksInsertFailed: 'No se pudo crear la hoja {sheet}.', appMergeWorkbooksLocked: 'La estructura del libro está bloqueada; no se puede combinar.' },
  th: { appMergeWorkbooks: 'รวมเวิร์กบุ๊ก', appMergeWorkbooksTip: 'นำชีตจากไฟล์ Excel อื่นมารวมในเวิร์กบุ๊กนี้', appMergeWorkbooksPicking: 'เลือกไฟล์ที่จะรวม…', appMergeWorkbooksReading: 'กำลังนำเข้า {sheet} จาก {file}…', appMergeWorkbooksDone: 'รวม {sheets} ชีตจาก {files} ไฟล์แล้ว (สูตรถูกนำเข้าเป็นค่า)', appMergeWorkbooksFailed: 'รวมเวิร์กบุ๊กไม่สำเร็จ', appMergeWorkbooksInsertFailed: 'ไม่สามารถสร้างชีต {sheet} ได้', appMergeWorkbooksLocked: 'โครงสร้างเวิร์กบุ๊กถูกล็อก จึงรวมไม่ได้' },
  id: { appMergeWorkbooks: 'Gabungkan Buku Kerja', appMergeWorkbooksTip: 'Tambahkan sheet dari file Excel lain ke buku kerja ini', appMergeWorkbooksPicking: 'Pilih file yang akan digabungkan…', appMergeWorkbooksReading: 'Mengimpor {sheet} dari {file}…', appMergeWorkbooksDone: '{sheets} sheet dari {files} file digabungkan (rumus diimpor sebagai nilai).', appMergeWorkbooksFailed: 'Gagal menggabungkan buku kerja.', appMergeWorkbooksInsertFailed: 'Tidak dapat membuat sheet {sheet}.', appMergeWorkbooksLocked: 'Struktur buku kerja terkunci; penggabungan tidak tersedia.' },
  ru: { appMergeWorkbooks: 'Объединить книги', appMergeWorkbooksTip: 'Добавить листы из других файлов Excel в эту книгу', appMergeWorkbooksPicking: 'Выберите файлы для объединения…', appMergeWorkbooksReading: 'Импорт {sheet} из {file}…', appMergeWorkbooksDone: 'Объединено листов: {sheets} из файлов: {files} (формулы импортированы как значения).', appMergeWorkbooksFailed: 'Не удалось объединить книги.', appMergeWorkbooksInsertFailed: 'Не удалось создать лист {sheet}.', appMergeWorkbooksLocked: 'Структура книги защищена; объединение недоступно.' },
  ar: { appMergeWorkbooks: 'دمج المصنفات', appMergeWorkbooksTip: 'إضافة أوراق من ملفات Excel أخرى إلى هذا المصنف', appMergeWorkbooksPicking: 'اختر الملفات المراد دمجها…', appMergeWorkbooksReading: 'جارٍ استيراد {sheet} من {file}…', appMergeWorkbooksDone: 'تم دمج {sheets} ورقة من {files} ملفات (تم استيراد الصيغ كقيم).', appMergeWorkbooksFailed: 'فشل دمج المصنفات.', appMergeWorkbooksInsertFailed: 'تعذر إنشاء الورقة {sheet}.', appMergeWorkbooksLocked: 'بنية المصنف مقفلة؛ الدمج غير متاح.' },
  pt: { appMergeWorkbooks: 'Mesclar pastas de trabalho', appMergeWorkbooksTip: 'Adicionar planilhas de outros arquivos do Excel a esta pasta de trabalho', appMergeWorkbooksPicking: 'Escolha os arquivos para mesclar…', appMergeWorkbooksReading: 'Importando {sheet} de {file}…', appMergeWorkbooksDone: '{sheets} planilhas de {files} arquivos mescladas (fórmulas importadas como valores).', appMergeWorkbooksFailed: 'Falha ao mesclar as pastas de trabalho.', appMergeWorkbooksInsertFailed: 'Não foi possível criar a planilha {sheet}.', appMergeWorkbooksLocked: 'A estrutura da pasta está bloqueada; não é possível mesclar.' },
  it: { appMergeWorkbooks: 'Unisci cartelle di lavoro', appMergeWorkbooksTip: 'Aggiungi i fogli di altri file Excel a questa cartella di lavoro', appMergeWorkbooksPicking: 'Scegli i file da unire…', appMergeWorkbooksReading: 'Importazione di {sheet} da {file}…', appMergeWorkbooksDone: 'Uniti {sheets} fogli da {files} file (formule importate come valori).', appMergeWorkbooksFailed: 'Unione delle cartelle di lavoro non riuscita.', appMergeWorkbooksInsertFailed: 'Impossibile creare il foglio {sheet}.', appMergeWorkbooksLocked: 'La struttura della cartella è bloccata; unione non disponibile.' },
  pl: { appMergeWorkbooks: 'Scal skoroszyty', appMergeWorkbooksTip: 'Dodaj arkusze z innych plików Excel do tego skoroszytu', appMergeWorkbooksPicking: 'Wybierz pliki do scalenia…', appMergeWorkbooksReading: 'Importowanie {sheet} z {file}…', appMergeWorkbooksDone: 'Scalono {sheets} arkuszy z {files} plików (formuły zaimportowano jako wartości).', appMergeWorkbooksFailed: 'Scalanie skoroszytów nie powiodło się.', appMergeWorkbooksInsertFailed: 'Nie można utworzyć arkusza {sheet}.', appMergeWorkbooksLocked: 'Struktura skoroszytu jest zablokowana; scalanie jest niedostępne.' },
  nl: { appMergeWorkbooks: 'Werkmappen samenvoegen', appMergeWorkbooksTip: 'Bladen uit andere Excel-bestanden aan deze werkmap toevoegen', appMergeWorkbooksPicking: 'Kies bestanden om samen te voegen…', appMergeWorkbooksReading: '{sheet} uit {file} importeren…', appMergeWorkbooksDone: '{sheets} bladen uit {files} bestanden samengevoegd (formules als waarden geïmporteerd).', appMergeWorkbooksFailed: 'Samenvoegen van werkmappen mislukt.', appMergeWorkbooksInsertFailed: 'Kan blad {sheet} niet maken.', appMergeWorkbooksLocked: 'De werkmapstructuur is vergrendeld; samenvoegen is niet beschikbaar.' },
  ms: { appMergeWorkbooks: 'Gabung Buku Kerja', appMergeWorkbooksTip: 'Tambah helaian daripada fail Excel lain ke buku kerja ini', appMergeWorkbooksPicking: 'Pilih fail untuk digabungkan…', appMergeWorkbooksReading: 'Mengimport {sheet} daripada {file}…', appMergeWorkbooksDone: '{sheets} helaian daripada {files} fail digabungkan (formula diimport sebagai nilai).', appMergeWorkbooksFailed: 'Gagal menggabungkan buku kerja.', appMergeWorkbooksInsertFailed: 'Tidak dapat mencipta helaian {sheet}.', appMergeWorkbooksLocked: 'Struktur buku kerja dikunci; penggabungan tidak tersedia.' },
  he: { appMergeWorkbooks: 'מיזוג חוברות עבודה', appMergeWorkbooksTip: 'הוספת גיליונות מקובצי Excel אחרים לחוברת העבודה הזו', appMergeWorkbooksPicking: 'בחרו קבצים למיזוג…', appMergeWorkbooksReading: 'מייבא את {sheet} מתוך {file}…', appMergeWorkbooksDone: 'מוזגו {sheets} גיליונות מ־{files} קבצים (נוסחאות יובאו כערכים).', appMergeWorkbooksFailed: 'מיזוג חוברות העבודה נכשל.', appMergeWorkbooksInsertFailed: 'לא ניתן ליצור את הגיליון {sheet}.', appMergeWorkbooksLocked: 'מבנה חוברת העבודה נעול; המיזוג אינו זמין.' },
  hi: { appMergeWorkbooks: 'वर्कबुक मर्ज करें', appMergeWorkbooksTip: 'अन्य Excel फ़ाइलों की शीट इस वर्कबुक में जोड़ें', appMergeWorkbooksPicking: 'मर्ज करने के लिए फ़ाइलें चुनें…', appMergeWorkbooksReading: '{file} से {sheet} आयात हो रही है…', appMergeWorkbooksDone: '{files} फ़ाइलों से {sheets} शीट मर्ज हुईं (सूत्र मानों के रूप में आयात हुए)।', appMergeWorkbooksFailed: 'वर्कबुक मर्ज नहीं हो सकीं।', appMergeWorkbooksInsertFailed: 'शीट {sheet} नहीं बनाई जा सकी।', appMergeWorkbooksLocked: 'वर्कबुक संरचना लॉक है; मर्ज उपलब्ध नहीं है।' },
  'zh-TW': { appMergeWorkbooks: '合併活頁簿', appMergeWorkbooksTip: '將其他 Excel 檔案的工作表併入目前活頁簿', appMergeWorkbooksPicking: '選擇要合併的檔案…', appMergeWorkbooksReading: '正在匯入 {file} 的 {sheet}…', appMergeWorkbooksDone: '已合併 {files} 個檔案的 {sheets} 張工作表（公式已轉為數值）。', appMergeWorkbooksFailed: '合併活頁簿失敗。', appMergeWorkbooksInsertFailed: '無法建立工作表 {sheet}。', appMergeWorkbooksLocked: '活頁簿結構已鎖定，目前無法合併。' },
})
