// Modified by TandemFolio contributors: native streamed-find status copy.
import { defineStrings } from '@genoffice/i18n'

/** Status shown when bounded native Find cannot scan the complete workbook. */
export const nativeFindStrings = defineStrings({
  zh: { appFindScanTruncated: '查找已扫描 {cells} 个单元格；工作簿过大，结果可能不完整。', appErrorCheckingDetail: '扫描当前表中的错误值', appErrorsFound: '发现 {count} 个错误，已定位 {cell}: {value}', appCheckingErrors: '正在扫描整个工作表的错误…', appNoErrorsFound: '未发现错误值。' },
  en: { appFindScanTruncated: 'Find scanned {cells} cells; this large workbook may have more matches.', appErrorCheckingDetail: 'Scan the sheet for error values', appErrorsFound: '{count} errors — at {cell}: {value}', appCheckingErrors: 'Scanning the whole sheet for errors…', appNoErrorsFound: 'No error values found.' },
  ja: { appFindScanTruncated: '検索で {cells} セルを走査しました。大きなブックのため結果が不完全な場合があります。', appErrorCheckingDetail: 'シート内のエラー値をスキャン', appErrorsFound: '{count} 件のエラー — {cell}: {value}', appCheckingErrors: 'シート全体のエラーをスキャンしています…', appNoErrorsFound: 'エラー値は見つかりませんでした。' },
  ko: { appFindScanTruncated: '찾기에서 {cells}개 셀을 검사했습니다. 큰 통합 문서에는 결과가 더 있을 수 있습니다.', appErrorCheckingDetail: '시트의 오류 값 검사', appErrorsFound: '오류 {count}개 — {cell}: {value}', appCheckingErrors: '시트 전체의 오류를 검사하는 중…', appNoErrorsFound: '오류 값이 없습니다.' },
  fr: { appFindScanTruncated: 'La recherche a analysé {cells} cellules ; ce grand classeur peut contenir d’autres résultats.', appErrorCheckingDetail: 'Rechercher les valeurs d’erreur de la feuille', appErrorsFound: '{count} erreurs — à {cell} : {value}', appCheckingErrors: 'Recherche d’erreurs dans toute la feuille…', appNoErrorsFound: 'Aucune valeur d’erreur trouvée.' },
  de: { appFindScanTruncated: 'Die Suche hat {cells} Zellen geprüft; diese große Arbeitsmappe kann weitere Treffer enthalten.', appErrorCheckingDetail: 'Blatt auf Fehlerwerte prüfen', appErrorsFound: '{count} Fehler — bei {cell}: {value}', appCheckingErrors: 'Das ganze Blatt wird auf Fehler gescannt…', appNoErrorsFound: 'Keine Fehlerwerte gefunden.' },
  es: { appFindScanTruncated: 'Buscar examinó {cells} celdas; este libro grande puede contener más coincidencias.', appErrorCheckingDetail: 'Buscar valores de error en la hoja', appErrorsFound: '{count} errores — en {cell}: {value}', appCheckingErrors: 'Buscando errores en toda la hoja…', appNoErrorsFound: 'No se encontraron valores de error.' },
  th: { appFindScanTruncated: 'ค้นหาตรวจสอบแล้ว {cells} เซลล์ สมุดงานขนาดใหญ่นี้อาจมีผลลัพธ์เพิ่มเติม', appErrorCheckingDetail: 'สแกนหาค่าผิดพลาดในชีต', appErrorsFound: 'พบข้อผิดพลาด {count} รายการ — ที่ {cell}: {value}', appCheckingErrors: 'กำลังสแกนหาข้อผิดพลาดทั่วทั้งชีต…', appNoErrorsFound: 'ไม่พบค่าผิดพลาด' },
  id: { appFindScanTruncated: 'Pencarian memindai {cells} sel; buku kerja besar ini mungkin memiliki hasil lain.', appErrorCheckingDetail: 'Pindai nilai kesalahan di lembar', appErrorsFound: '{count} kesalahan — di {cell}: {value}', appCheckingErrors: 'Memindai kesalahan di seluruh lembar…', appNoErrorsFound: 'Tidak ada nilai kesalahan.' },
  ru: { appFindScanTruncated: 'Поиск проверил {cells} ячеек; в этой большой книге могут быть другие совпадения.', appErrorCheckingDetail: 'Найти значения ошибок на листе', appErrorsFound: 'Ошибок: {count} — в {cell}: {value}', appCheckingErrors: 'Идёт поиск ошибок по всему листу…', appNoErrorsFound: 'Значений ошибок не найдено.' },
  ar: { appFindScanTruncated: 'فحص البحث {cells} خلية؛ قد يحتوي هذا المصنف الكبير على نتائج أخرى.', appErrorCheckingDetail: 'فحص الورقة بحثًا عن قيم الخطأ', appErrorsFound: '{count} من الأخطاء — في {cell}: {value}', appCheckingErrors: 'جارٍ فحص الورقة بالكامل بحثًا عن أخطاء…', appNoErrorsFound: 'لم يتم العثور على قيم خطأ.' },
  pt: { appFindScanTruncated: 'A pesquisa examinou {cells} células; esta pasta de trabalho grande pode ter mais resultados.', appErrorCheckingDetail: 'Verificar valores de erro na planilha', appErrorsFound: '{count} erros — em {cell}: {value}', appCheckingErrors: 'Procurando erros na planilha inteira…', appNoErrorsFound: 'Nenhum valor de erro encontrado.' },
  it: { appFindScanTruncated: 'La ricerca ha esaminato {cells} celle; questa cartella di lavoro grande potrebbe contenere altri risultati.', appErrorCheckingDetail: 'Cerca valori di errore nel foglio', appErrorsFound: '{count} errori — in {cell}: {value}', appCheckingErrors: 'Ricerca errori in corso su tutto il foglio…', appNoErrorsFound: 'Nessun valore di errore trovato.' },
  pl: { appFindScanTruncated: 'Wyszukiwanie sprawdziło {cells} komórek; ten duży skoroszyt może zawierać więcej wyników.', appErrorCheckingDetail: 'Skanuj arkusz w poszukiwaniu błędów', appErrorsFound: 'Błędy: {count} — w {cell}: {value}', appCheckingErrors: 'Skanowanie całego arkusza w poszukiwaniu błędów…', appNoErrorsFound: 'Nie znaleziono wartości błędów.' },
  nl: { appFindScanTruncated: 'Zoeken heeft {cells} cellen gecontroleerd; deze grote werkmap kan meer resultaten bevatten.', appErrorCheckingDetail: 'Blad scannen op foutwaarden', appErrorsFound: '{count} fouten — bij {cell}: {value}', appCheckingErrors: 'Het hele werkblad wordt op fouten gecontroleerd…', appNoErrorsFound: 'Geen foutwaarden gevonden.' },
  ms: { appFindScanTruncated: 'Carian mengimbas {cells} sel; buku kerja besar ini mungkin mempunyai hasil lain.', appErrorCheckingDetail: 'Imbas nilai ralat dalam helaian', appErrorsFound: '{count} ralat — di {cell}: {value}', appCheckingErrors: 'Mengimbas ralat di seluruh helaian…', appNoErrorsFound: 'Tiada nilai ralat ditemui.' },
  he: { appFindScanTruncated: 'החיפוש סרק {cells} תאים; בחוברת עבודה גדולה זו עשויות להיות התאמות נוספות.', appErrorCheckingDetail: 'סריקת הגיליון לערכי שגיאה', appErrorsFound: '{count} שגיאות — ב-{cell}: {value}', appCheckingErrors: 'סורקים את הגיליון כולו לאיתור שגיאות…', appNoErrorsFound: 'לא נמצאו ערכי שגיאה.' },
  hi: { appFindScanTruncated: 'खोज ने {cells} सेल जाँचे; इस बड़ी कार्यपुस्तिका में और परिणाम हो सकते हैं।', appErrorCheckingDetail: 'शीट में त्रुटि मान खोजें', appErrorsFound: '{count} त्रुटियाँ — {cell} पर: {value}', appCheckingErrors: 'पूरी शीट में त्रुटियों के लिए स्कैन हो रहा है…', appNoErrorsFound: 'कोई त्रुटि मान नहीं मिला।' },
  'zh-TW': { appFindScanTruncated: '尋找已掃描 {cells} 個儲存格；活頁簿過大，結果可能不完整。', appErrorCheckingDetail: '掃描目前工作表中的錯誤值', appErrorsFound: '發現 {count} 個錯誤，已定位 {cell}: {value}', appCheckingErrors: '正在掃描整個工作表的錯誤…', appNoErrorsFound: '未發現錯誤值。' },
})
