import type { OperationCatalog } from '@tandemfolio/operation-contract'

const coordinateSchema = { type: 'number', minimum: -10_000_000, maximum: 10_000_000 } as const
const unitSchema = { type: 'number', minimum: 0, maximum: 1 } as const
const byteSchema = { type: 'integer', minimum: 0, maximum: 255 } as const
const pageIndexSchema = { type: 'integer', minimum: 0, maximum: 999_999 } as const
const pointSchema = {
  type: 'array',
  minItems: 2,
  maxItems: 2,
  items: coordinateSchema,
} as const
const rectSchema = {
  type: 'array',
  minItems: 4,
  maxItems: 4,
  items: coordinateSchema,
} as const
const rgbUnitSchema = {
  type: 'array',
  minItems: 3,
  maxItems: 3,
  items: unitSchema,
} as const
const rgbByteSchema = {
  type: 'array',
  minItems: 3,
  maxItems: 3,
  items: byteSchema,
} as const
const idOutputSchema = {
  type: 'object',
  properties: { id: { type: 'string', minLength: 1, maxLength: 128 } },
  required: ['id'],
  additionalProperties: false,
} as const
const drawingSchema = {
  type: 'object',
  properties: {
    kind: { type: 'string', enum: ['ink', 'rect', 'ellipse', 'line', 'arrow', 'image', 'note'] },
    pageIndex: pageIndexSchema,
    color: rgbUnitSchema,
    width: { type: 'number', minimum: 0.1, maximum: 144 },
    paths: {
      type: 'array',
      minItems: 1,
      maxItems: 256,
      items: {
        type: 'array',
        minItems: 4,
        maxItems: 65_536,
        items: coordinateSchema,
      },
    },
    rect: rectSchema,
    from: pointSchema,
    to: pointSchema,
    image: { type: 'string', minLength: 1, maxLength: 28_000_000 },
    at: pointSchema,
    contents: { type: 'string', minLength: 1, maxLength: 100_000 },
    formFieldName: { type: 'string', minLength: 1, maxLength: 512 },
  },
  required: ['kind', 'pageIndex'],
  additionalProperties: false,
} as const
const textInsertProperties = {
  pageIndex: pageIndexSchema,
  origin: pointSchema,
  text: { type: 'string', minLength: 1, maxLength: 1_000_000 },
  fontSize: { type: 'number', minimum: 1, maximum: 1_000 },
  color: rgbByteSchema,
  font: { type: 'string', minLength: 1, maxLength: 128 },
  bold: { type: 'boolean' },
  italic: { type: 'boolean' },
  lineLeading: { type: 'number', minimum: 0.1, maximum: 10_000 },
  lineXOffsets: {
    type: 'array',
    maxItems: 100_000,
    items: coordinateSchema,
  },
  align: { type: 'string', enum: ['left', 'center', 'right'] },
  rotate: { type: 'integer', enum: [0, 90, 180, 270] },
} as const
const imageProperties = {
  pageIndex: pageIndexSchema,
  rect: rectSchema,
  image: { type: 'string', minLength: 1, maxLength: 28_000_000 },
  layer: { type: 'string', enum: ['belowText', 'aboveText'] },
  rotate: { type: 'integer', enum: [0, 90, 180, 270] },
} as const

export const pdfOperationCatalog = {
  format: 'pdf',
  operations: [
    {
      id: 'pdf.annotation.delete_saved',
      format: 'pdf',
      family: 'annotation',
      summary: 'Delete one exact saved PDF text-markup annotation.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          pageIndex: { type: 'integer', minimum: 0 },
          objNum: { type: 'integer', minimum: 1 },
          subtype: {
            type: 'string',
            enum: ['highlight', 'underline', 'strikeout'],
          },
          rect: {
            type: 'array',
            minItems: 4,
            maxItems: 4,
            items: { type: 'number' },
          },
        },
        required: ['pageIndex', 'objNum', 'subtype', 'rect'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          deleted: { type: 'integer', minimum: 1 },
        },
        required: ['deleted'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.document.set_metadata',
      format: 'pdf',
      family: 'document',
      summary: 'Set the editable PDF document metadata fields to explicit final values.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          title: { type: 'string', maxLength: 10_000 },
          author: { type: 'string', maxLength: 10_000 },
          subject: { type: 'string', maxLength: 10_000 },
          keywords: { type: 'string', maxLength: 100_000 },
        },
        required: ['title', 'author', 'subject', 'keywords'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.drawing.add',
      format: 'pdf',
      family: 'drawing',
      summary: 'Add one bounded drawing, note, or visual signature annotation.',
      visibility: 'agent',
      inputSchema: drawingSchema,
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.drawing.update',
      format: 'pdf',
      family: 'drawing',
      summary: 'Replace one pending drawing with an explicit final drawing state.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'string', minLength: 1, maxLength: 128 },
          drawing: drawingSchema,
        },
        required: ['id', 'drawing'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.form.set_value',
      format: 'pdf',
      family: 'form',
      summary: 'Set one named AcroForm field to an explicit final value.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          name: { type: 'string', minLength: 1, maxLength: 512 },
          kind: { type: 'string', enum: ['text', 'checkbox', 'radio', 'choice'] },
          value: { type: 'string', maxLength: 1_000_000 },
          checked: { type: 'boolean' },
        },
        required: ['name', 'kind'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { field: { type: 'string', minLength: 1, maxLength: 512 } },
        required: ['field'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.history.redo',
      format: 'pdf',
      family: 'history',
      summary: 'Redo the latest reverted edit in the mounted PDF history.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { redone: { type: 'boolean', enum: [true] } },
        required: ['redone'],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.image.delete',
      format: 'pdf',
      family: 'image',
      summary: 'Delete one exact content-stream image addressed by its source bounds.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: { pageIndex: pageIndexSchema, oldRect: rectSchema },
        required: ['pageIndex', 'oldRect'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.image.insert',
      format: 'pdf',
      family: 'image',
      summary: 'Insert bounded PNG bytes into one exact page rectangle and z-band.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: imageProperties,
        required: ['pageIndex', 'rect', 'image', 'layer'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.image.replace',
      format: 'pdf',
      family: 'image',
      summary: 'Replace one exact content-stream image with bounded PNG bytes and final geometry.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          ...imageProperties,
          oldRect: rectSchema,
          quarterTurns: { type: 'integer', minimum: 0, maximum: 3 },
        },
        required: ['pageIndex', 'oldRect', 'rect', 'image'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.image.transform',
      format: 'pdf',
      family: 'image',
      summary: 'Set final geometry, z-band, and quarter-turns for one exact content-stream image.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          pageIndex: pageIndexSchema,
          oldRect: rectSchema,
          rect: rectSchema,
          layer: { type: 'string', enum: ['belowText', 'aboveText'] },
          quarterTurns: { type: 'integer', minimum: 0, maximum: 3 },
        },
        required: ['pageIndex', 'oldRect', 'rect'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.markup.add',
      format: 'pdf',
      family: 'markup',
      summary: 'Add one bounded text-markup annotation from exact PDF-space quads.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          pageIndex: pageIndexSchema,
          type: { type: 'string', enum: ['highlight', 'underline', 'strikeout'] },
          color: rgbUnitSchema,
          quads: {
            type: 'array',
            minItems: 1,
            maxItems: 10_000,
            items: {
              type: 'array',
              minItems: 8,
              maxItems: 8,
              items: coordinateSchema,
            },
          },
        },
        required: ['pageIndex', 'type', 'color', 'quads'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.page.insert',
      format: 'pdf',
      family: 'page',
      summary: 'Insert every page from one local PDF after an exact original page.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string', minLength: 1, maxLength: 32_768 },
          afterPageIndex: { type: 'integer', minimum: -1, maximum: 999_999 },
        },
        required: ['path', 'afterPageIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { insertedCount: { type: 'integer', minimum: 1, maximum: 1_000_000 } },
        required: ['insertedCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection', 'persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.page.insert_staged',
      format: 'pdf',
      family: 'page',
      summary: 'Insert Broker-hydrated PDF bytes after an exact original page.',
      visibility: 'internal',
      inputSchema: {
        type: 'object',
        properties: {
          blobId: { type: 'string', minLength: 1, maxLength: 512 },
          name: { type: 'string', minLength: 1, maxLength: 512 },
          size: { type: 'integer', minimum: 1, maximum: 100_000_000 },
          data: {
            type: 'object',
            description: 'Hydrated ArrayBuffer supplied by the live-session host bridge.',
            properties: {},
            required: [],
            additionalProperties: false,
          },
          afterPageIndex: { type: 'integer', minimum: -1, maximum: 999_999 },
        },
        required: ['blobId', 'name', 'size', 'data', 'afterPageIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { insertedCount: { type: 'integer', minimum: 1, maximum: 1_000_000 } },
        required: ['insertedCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection', 'persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.page.delete',
      format: 'pdf',
      family: 'page',
      summary: 'Delete one exact original page while preserving at least one page.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: { pageIndex: pageIndexSchema },
        required: ['pageIndex'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { deletedPage: pageIndexSchema },
        required: ['deletedPage'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.page.reorder',
      format: 'pdf',
      family: 'page',
      summary: 'Set the explicit final order of all non-deleted original pages.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          pageOrder: {
            type: 'array',
            minItems: 1,
            maxItems: 1_000_000,
            items: pageIndexSchema,
          },
        },
        required: ['pageOrder'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { pageCount: { type: 'integer', minimum: 1, maximum: 1_000_000 } },
        required: ['pageCount'],
        additionalProperties: false,
      },
      risk: 'high',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.page.set_rotation',
      format: 'pdf',
      family: 'page',
      summary: 'Set one original page to an explicit final clockwise rotation.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          pageIndex: pageIndexSchema,
          rotation: { type: 'integer', enum: [0, 90, 180, 270] },
        },
        required: ['pageIndex', 'rotation'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { rotation: { type: 'integer', enum: [0, 90, 180, 270] } },
        required: ['rotation'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.pending.delete',
      format: 'pdf',
      family: 'pending',
      summary: 'Delete one exact pending edit by bounded kind and operation-local id.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          kind: {
            type: 'string',
            enum: ['markup', 'drawing', 'textEdit', 'textInsert', 'imageEdit'],
          },
          id: { type: 'string', minLength: 1, maxLength: 128 },
        },
        required: ['kind', 'id'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.stamp.set',
      format: 'pdf',
      family: 'stamp',
      summary: 'Set or clear the document watermark and header/footer final configuration.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          watermark: {
            type: ['object', 'null'],
            properties: {
              text: { type: 'string', maxLength: 10_000 },
              angle: { type: 'number', minimum: -360, maximum: 360 },
              opacity: unitSchema,
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
              sizeRatio: { type: 'number', minimum: 0.001, maximum: 1 },
            },
            required: ['text', 'angle', 'opacity', 'color', 'sizeRatio'],
            additionalProperties: false,
          },
          headerFooter: {
            type: ['object', 'null'],
            properties: {
              headerLeft: { type: 'string', maxLength: 10_000 },
              headerCenter: { type: 'string', maxLength: 10_000 },
              headerRight: { type: 'string', maxLength: 10_000 },
              footerLeft: { type: 'string', maxLength: 10_000 },
              footerCenter: { type: 'string', maxLength: 10_000 },
              footerRight: { type: 'string', maxLength: 10_000 },
              pageNumber: { type: 'boolean' },
              startAt: { type: 'integer', minimum: -1_000_000, maximum: 1_000_000 },
              fontSize: { type: 'number', minimum: 1, maximum: 144 },
              color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
            },
            required: [
              'headerLeft',
              'headerCenter',
              'headerRight',
              'footerLeft',
              'footerCenter',
              'footerRight',
              'pageNumber',
              'startAt',
              'fontSize',
              'color',
            ],
            additionalProperties: false,
          },
        },
        required: ['watermark', 'headerFooter'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean', enum: [true] } },
        required: ['updated'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.static_form.set',
      format: 'pdf',
      family: 'static_form',
      summary: 'Insert or replace one bitmap-backed static form fill with explicit metadata.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'string', minLength: 1, maxLength: 128 },
          kind: { type: 'string', enum: ['text', 'check', 'cross'] },
          pageIndex: pageIndexSchema,
          rect: rectSchema,
          oldRect: rectSchema,
          image: { type: 'string', minLength: 1, maxLength: 28_000_000 },
          text: { type: 'string', maxLength: 1_000_000 },
          fontSize: { type: 'number', minimum: 1, maximum: 1_000 },
          color: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
          align: { type: 'string', enum: ['left', 'center', 'right'] },
        },
        required: ['id', 'kind', 'pageIndex', 'rect', 'image'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.text.insert',
      format: 'pdf',
      family: 'text',
      summary: 'Insert one bounded searchable text object at an exact PDF-space origin.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: textInsertProperties,
        required: ['pageIndex', 'origin', 'text', 'fontSize', 'color'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.text.replace',
      format: 'pdf',
      family: 'text',
      summary: 'Replace exact bounded page text and preserve optional final text formatting.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          pageIndex: pageIndexSchema,
          rect: rectSchema,
          oldText: { type: 'string', minLength: 1, maxLength: 1_000_000 },
          newText: { type: 'string', minLength: 1, maxLength: 1_000_000 },
          fontSize: { type: 'number', minimum: 1, maximum: 1_000 },
          newFontSize: { type: 'number', minimum: 1, maximum: 1_000 },
          newColor: rgbByteSchema,
          colorRuns: {
            type: 'array',
            maxItems: 100_000,
            items: {
              type: 'object',
              properties: {
                start: { type: 'integer', minimum: 0, maximum: 1_000_000 },
                end: { type: 'integer', minimum: 0, maximum: 1_000_000 },
                color: rgbByteSchema,
              },
              required: ['start', 'end', 'color'],
              additionalProperties: false,
            },
          },
          newFont: { type: 'string', minLength: 1, maxLength: 128 },
          newBold: { type: 'boolean' },
          newItalic: { type: 'boolean' },
          origin: pointSchema,
          lineLeading: { type: 'number', minimum: 0.1, maximum: 10_000 },
          lineXOffsets: { type: 'array', maxItems: 100_000, items: coordinateSchema },
          align: { type: 'string', enum: ['left', 'center', 'right'] },
          blockSource: { type: 'string', maxLength: 1_000_000 },
        },
        required: ['pageIndex', 'rect', 'oldText', 'newText', 'fontSize'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.text.update_inserted',
      format: 'pdf',
      family: 'text',
      summary: 'Replace one pending inserted-text object with an explicit final state.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'string', minLength: 1, maxLength: 128 },
          text: {
            type: 'object',
            properties: textInsertProperties,
            required: ['pageIndex', 'origin', 'text', 'fontSize', 'color'],
            additionalProperties: false,
          },
        },
        required: ['id', 'text'],
        additionalProperties: false,
      },
      outputSchema: idOutputSchema,
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: true,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.document.load_staged',
      format: 'pdf',
      family: 'document',
      summary: 'Load staged PDF bytes into the active editor.',
      visibility: 'internal',
      inputSchema: {
        type: 'object',
        properties: {
          blobId: { type: 'string' },
          name: { type: 'string' },
          size: { type: 'integer', minimum: 0 },
          data: {
            type: 'object',
            description: 'Hydrated ArrayBuffer supplied by the live-session host bridge.',
            properties: {},
            required: [],
            additionalProperties: false,
          },
        },
        required: ['blobId', 'name', 'size', 'data'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          opened: { type: 'string' },
        },
        required: ['opened'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.document.save',
      format: 'pdf',
      family: 'document',
      summary: 'Save the active PDF document.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          saved: { type: 'boolean', enum: [true] },
        },
        required: ['saved'],
        additionalProperties: false,
      },
      risk: 'medium',
      context: ['document'],
      effects: ['persistence'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
    {
      id: 'pdf.history.undo',
      format: 'pdf',
      family: 'history',
      summary: 'Undo the latest edit in the mounted PDF history.',
      visibility: 'agent',
      inputSchema: {
        type: 'object',
        properties: {},
        required: [],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          undone: { type: 'boolean', enum: [true] },
        },
        required: ['undone'],
        additionalProperties: false,
      },
      risk: 'low',
      context: ['document'],
      effects: ['document', 'selection'],
      mutates: true,
      undoable: false,
      atomic: true,
      compatibilityAliases: [],
    },
  ],
} as const satisfies OperationCatalog

export default pdfOperationCatalog
