export const releaseMeasurementMatrix = {
  formats: ['docx', 'markdown', 'xlsx', 'pptx', 'pdf'],
  fixtureSizes: ['small', 'medium', 'large'],
  measurements: [
    'pinnedUpstreamVisual',
    'coldStart',
    'openDocument',
    'interaction',
    'ack.pollWait',
    'ack.hydrate',
    'ack.execute',
    'ack.transport',
    'markdown.load.decode',
    'markdown.load.parse',
    'markdown.load.tiptapStateInstall',
    'markdown.load.reactCommit',
    'xlsx.coldStart.bootstrap',
    'xlsx.coldStart.univerCreate',
    'xlsx.coldStart.worksheetInstall',
    'xlsx.coldStart.firstCommit',
    'xlsx.bootstrap.resourceReceive',
    'xlsx.bootstrap.moduleGraphReady',
    'xlsx.bootstrap.reactMount',
    'peakJsHeap',
    'peakRendererMemory',
  ],
  defaultSamples: { coldStart: 7, openDocument: 7, interaction: 21 },
} as const
